const scenarios=[
  {signal:'Client says: “My dog is breathing strangely.”',response:'Stay calm, confirm a callback number, collect concise observations, and move the call to the clinic’s approved urgent-care pathway.',questions:['What are you seeing right now?','When did the change begin?','Is your pet responsive and able to move?'],handoff:'Document the client’s exact words, time, callback number, and the observations requested by the clinical team.',boundary:'The CSR gathers and routes information. Diagnosis and medical direction stay with licensed clinical staff.'},
  {signal:'Client says: “Why is this so expensive?”',response:'Acknowledge the concern without becoming defensive, clarify what the estimate includes, and identify the next person who can answer medical or financing questions.',questions:['Which part of the estimate would you like clarified first?','Would a line-by-line explanation help?','Should I connect you with the care team about priorities?'],handoff:'Record the concern, what was explained, what remains unanswered, and who owns the follow-up.',boundary:'Clear language supports informed decisions without minimizing cost or promising an outcome.'},
  {signal:'Client says: “No one called me back.”',response:'Validate the missed expectation, avoid blame, establish the immediate need, and give one concrete next step with a realistic time window.',questions:['What update were you expecting?','What is the best number to use now?','Is there a new concern the team should know about?'],handoff:'Capture the original promise, present concern, preferred contact method, and the person accepting ownership.',boundary:'Empathy is not an admission of fault; it is recognition of the client’s experience.'},
  {signal:'Client says: “I don’t know what I’m supposed to do.”',response:'Slow the conversation, use plain language, offer one decision at a time, and make space for silence without disappearing from the call.',questions:['Would you like me to explain the next step slowly?','Is someone with you right now?','Would you prefer a moment before we continue?'],handoff:'Document only what the team needs to continue compassionate service—never the private details of a family’s grief.',boundary:'The toolkit supports humane communication; it does not replace medical, crisis, or mental-health professionals.'}
];
const tabs=[...document.querySelectorAll('[data-stage]')];
tabs.forEach((button,index)=>button.addEventListener('click',()=>{const s=scenarios[index];tabs.forEach((item,i)=>item.setAttribute('aria-selected',String(i===index)));document.querySelector('#scenario-signal').textContent=s.signal;document.querySelector('#scenario-response').textContent=s.response;document.querySelector('#scenario-questions').innerHTML=s.questions.map(q=>`<li>${q}</li>`).join('');document.querySelector('#scenario-handoff').textContent=s.handoff;document.querySelector('#scenario-boundary').textContent=s.boundary;}));
const filters=[...document.querySelectorAll('[data-filter]')],cards=[...document.querySelectorAll('[data-category]')];
filters.forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;filters.forEach(item=>item.classList.toggle('active',item===button));let total=0;cards.forEach(card=>{const show=filter==='All'||card.dataset.category===filter;card.hidden=!show;if(show)total++;});document.querySelector('#component-count').textContent=`Showing ${total} system component${total===1?'':'s'}`;}));
